Fixed "created" Metadata not defaulting to meeting start time
elan-ev/opencast-bigbluebutton-integration pull request #16
Opened 2021-04-28 09:50 UTC by Arnei

Resolves #10.

2021-05-09 09:44 UTC, Rillke requested changes
Syntax error: Each expression are delimited by semicolons(;) or newlines.

2021-05-09 09:44 UTC, Rillke commented on post-archive/post_archive.rb
> +                                        server: $oc_server, user: $oc_user, password: $oc_password)dublincore = OcDublincore::createDublincore(dc_data)
```suggestion
                                        server: $oc_server, user: $oc_user, password: $oc_password)
dublincore = OcDublincore::createDublincore(dc_data)
```

2021-05-09 10:05 UTC, Rillke commented
Hi @Arnei do you know why even after applying this patch, the stopped time is not displayed in the opencast admin UI?
![Screenshot from 2021-05-09 11-49-11](https://user-images.githubusercontent.com/2311611/117567991-d0e6e600-b0be-11eb-9344-250612945558.png)
![Screenshot from 2021-05-09 11-49-17](https://user-images.githubusercontent.com/2311611/117567994-d2181300-b0be-11eb-81db-65b64830baf7.png)

2021-05-09 10:14 UTC, Rillke requested changes
`parseDcMetadata` [expects args[:stopTime]](https://github.com/elan-ev/opencast-bigbluebutton-integration/blob/master/oc_modules/oc_dublincore.rb#L104)

2021-05-09 10:14 UTC, Rillke commented on post-archive/post_archive.rb
> +dc_data = OcDublincore::parseDcMetadata(meeting_metadata, startTime: real_start_time, endTime: real_end_time,
```suggestion
dc_data = OcDublincore::parseDcMetadata(meeting_metadata, startTime: real_start_time, stopTime: real_end_time,
```

2021-05-11 13:46 UTC, Arnei commented
Hi @Rillke, thanks for all the reviews! Regarding your question:

> Hi @Arnei do you know why even after applying this patch, the stopped time is not displayed in the opencast admin UI?

As far as I can tell, this problem started occuring with Opencast 9. I created a PR that should fix it https://github.com/elan-ev/opencast-bigbluebutton-integration/pull/31.

2021-05-11 14:04 UTC, Rillke commented
> As far as I can tell, this problem started occuring with Opencast 9. I created a PR that should fix it #31.

Oh, we have Opencast 8; right after the `s/end/stop/`Time fix, the dates and duration appeared correctly. But it's quite possible that Opencast 9 needs that temporal field. Thanks :)

2021-05-11 14:16 UTC, merged