Added option to send presentations as attachments to Opencast
elan-ev/opencast-bigbluebutton-integration pull request #21
Opened 2021-05-06 10:51 UTC by Arnei

Resolves #12

2021-05-09 10:22 UTC, Rillke requested changes

2021-05-09 10:22 UTC, Rillke commented on post-archive/post_archive.rb
> +  BigBlueButton.logger.info( "Adding Presentations as PDFs is either disabled or there were no presentations, skipping adding Presentations as PDFs.")
> or there were no presentations

There is no check whether PDFs exist as far as I can see.

2021-05-09 10:29 UTC, Rillke requested changes
Presenters might be surprised to find all their uploads in Opencast.

2021-05-09 10:29 UTC, Rillke commented on post-archive/post_archive.rb
> +# Adds the presentations from a meeting to the attachments in Opencast as PDF files
```suggestion
# Add all uploaded presentations from a meeting to the attachments in Opencast as PDF files.
# Please make sure to use this feature respectfully.
```

2021-05-11 10:13 UTC, Arnei commented on post-archive/post_archive.rb
> +  BigBlueButton.logger.info( "Adding Presentations as PDFs is either disabled or there were no presentations, skipping adding Presentations as PDFs.")
Right, thanks. Changed the log message.

2021-05-11 14:15 UTC, merged