Added debug.json to set of assets to help with server source tracing …
elan-ev/opencast-bigbluebutton-integration pull request #39
Opened 2021-10-27 13:49 UTC by metzenseifner

…when problems occur e.g. due to encoding

2021-11-04 13:52 UTC, metzenseifner commented
@Arnei I resolved the conflicts, and this code should be good to go and compatible with the new configuration file.

2021-11-16 09:29 UTC, hex-m commented
`createDebugJSONAtPath` is never called.

2021-11-16 11:11 UTC, metzenseifner commented
Corrected. Thanks.

2022-07-25 11:07 UTC, Arnei requested changes
My apologies for this way overdue review. Debug information to link Opencast events to the BBB servers whence they came seems to be very useful feature.

Unfortunately I can't merge this as is.

2022-07-25 11:07 UTC, Arnei commented on post-archive/post_archive.rb
> +                   :flavor => "json/debug",
Might be worthwhile to make it more obvious that this attachment is specifically for BBB debuggin, e.g `json/bbb-debug`

2023-04-10 20:11 UTC, closed without merging