Add support for new recording format "video"
elan-ev/opencast-bigbluebutton-integration pull request #59
Opened 2023-03-30 10:11 UTC by dennis531

Adds support for the new bbb recording format "video". This format creates a single video file `video-0.m4v` from the webcam videos and the presentation video. If the old format `presentation` and the new format are enabled as described below, the `post_publish` script will be executed for each format, in this case twice. Then both formats will be ingested into opencast.

### Steps to enable the new, single-file recording format "video" in BigBlueButton 2.6

1. Add packages
    ```bash
    apt-get install bbb-playback-video
    ```
2. Edit `/usr/local/bigbluebutton/core/scripts/bigbluebutton.yml`
    ```yaml=
    steps:
      archive: "sanity"
      sanity: "captions"
      captions:
        - "process:presentation"
        - "process:video"
      "process:presentation": "publish:presentation"
      "process:video": "publish:video"
    ```
3. Restart processes
    ```bash
    systemctl restart bbb-rap-resque-worker.service nginx
    ```

The latest documentation can be found at:

- https://docs.bigbluebutton.org/2.6/customize.html#install-additional-recording-processing-formats

2023-04-03 10:28 UTC, Arnei commented
Cool, that could make the post_publish workflow more attractive for some institutions.

Could you adjust the post publish documentation to reflect the changes? Also the link you provided to the BBB docs is dead :D

2023-04-05 07:10 UTC, Arnei requested changes

2023-04-05 07:10 UTC, Arnei commented on post-publish/README.md
> +    - Single file recording (see [Configure Single File Recording](#configure-single-file-recording))
Reads like it will send all of those, but actually it will either send the single file recording OR all the other stuff, correct?

2023-04-05 07:10 UTC, Arnei commented on post-publish/README.md
> +If it is not yet installed, add the line `gem 'rest-client'` to the `GEMFILE` located at `/usr/local/bigbluebutton/core/Gemfile`. Possibly, you also need to add `gem 'toml-rb'` and `gem 'shellwords'`
Why "possibly"? Do you mean "if not already present in the gemfile?

Also don't you have to run `bundle install` to actually install the gems?

2023-04-05 07:10 UTC, Arnei commented on post-publish/README.md
> +For more details, see [Install additional recording processing formats](https://docs.bigbluebutton.org/2.6/administration/customize#install-additional-recording-processing-formats).
Link is still dead :D "Page not found"

2023-04-05 07:10 UTC, Arnei commented on post-publish/README.md
> +The single file recording contains webcams, presentation and screensharing. This recording provides an alternative to the separate video files that are uploaded to Opencast. To process and transfer t
Also contains audio? Does it include the markings you can make with the whiteboard tools? I think potential users would benefit from a differentiated description on what is and isn't included "Single File Recording" and "Not single File Recording".

2023-04-05 07:10 UTC, Arnei commented on post-publish/README.md
> +    Alternative, if you don't want to process and upload the separate video files:
What seperate video files? I thought this was a single file recording? Could you make more clear what these arcane config settings do?

2023-04-05 08:51 UTC, dennis531 commented on post-publish/README.md
> +    - Single file recording (see [Configure Single File Recording](#configure-single-file-recording))
Which files are sent depends on the BBB configurations. More precisely on the configured steps in `bigbluebutton.yml`. The default in BBB are the old files (format: presentation). If both formats "presentation" and "video" are processed, all files will be send separately to opencast. In the latter case, opencast has two events.

2023-04-05 09:00 UTC, dennis531 commented on post-publish/README.md
> +If it is not yet installed, add the line `gem 'rest-client'` to the `GEMFILE` located at `/usr/local/bigbluebutton/core/Gemfile`. Possibly, you also need to add `gem 'toml-rb'` and `gem 'shellwords'`
"possibly" because I had the problem that my BBB did not contain these packages in the Gemfile and errors occurred without them. The included packages could depend on the BBB version. I replace "possibly".

`bundle install`: this step is necessary. Thanks, I add it to the Readme.

2023-04-05 09:06 UTC, Arnei commented on post-publish/README.md
> +    - Single file recording (see [Configure Single File Recording](#configure-single-file-recording))
Interesting. I thought the 
```
if (format == 'video') [...]
```

would make sure only one or the other is sent. Does that mean the post-publish script is run multiple times, once for "presentation" and once for "video"?

2023-04-05 09:08 UTC, dennis531 commented on post-publish/README.md
> +    - Single file recording (see [Configure Single File Recording](#configure-single-file-recording))
That is correct. BBB runs this script for each format.

2023-04-05 09:12 UTC, Arnei commented on post-publish/README.md
> +    - Single file recording (see [Configure Single File Recording](#configure-single-file-recording))
Huh, interesting. Thanks for the explanation.

2023-04-05 10:50 UTC, dennis531 commented on post-publish/README.md
> +For more details, see [Install additional recording processing formats](https://docs.bigbluebutton.org/2.6/administration/customize#install-additional-recording-processing-formats).
Seems like they periodically change their URLs

2023-04-05 10:56 UTC, dennis531 commented on post-publish/README.md
> +The single file recording contains webcams, presentation and screensharing. This recording provides an alternative to the separate video files that are uploaded to Opencast. To process and transfer t
Yes, audio and markings are included.

2023-04-05 11:43 UTC, dennis531 commented on post-publish/README.md
> +For more details, see [Install additional recording processing formats](https://docs.bigbluebutton.org/2.6/administration/customize#install-additional-recording-processing-formats).
I hope the new url is more persistent. Otherwise, the url should be removed.

2023-04-17 14:01 UTC, dennis531 commented
The requested changes should be resolved. Please check if the documentation is correct and understandable.

2023-04-21 09:55 UTC, Arnei reviewed
I tried to use this configuration
```
        steps:
            archive: "sanity"
            sanity: "captions"
            captions:
                - "process:presentation"
                - "process:video"
            "process:presentation": "publish:presentation"
            "process:video": "publish:video"
 ```
            
but only the single file recording made it into Opencast. The other recording does not seem to have made it, the Opencast Inspect WOH throws an error:
```
Exception message WorkflowOperationException: Mediapackage 20f1cccd-f655-4ae2-b1a6-cc801f780876 contains no media
```            

Did I do something wrong?

2023-04-21 09:57 UTC, Arnei commented
> The requested changes should be resolved. Please check if the documentation is correct and understandable.

Yup, looks good.

2023-04-21 10:35 UTC, dennis531 commented
> I tried to use this configuration
> 
> ```
>         steps:
>             archive: "sanity"
>             sanity: "captions"
>             captions:
>                 - "process:presentation"
>                 - "process:video"
>             "process:presentation": "publish:presentation"
>             "process:video": "publish:video"
> ```
> 
> but only the single file recording made it into Opencast. The other recording does not seem to have made it, the Opencast Inspect WOH throws an error:
> 
> ```
> Exception message WorkflowOperationException: Mediapackage 20f1cccd-f655-4ae2-b1a6-cc801f780876 contains no media
> ```
> 
> Did I do something wrong?

The settings seem to be correct. Which BBB version do you use? Can you locate a video file under `/var/bigbluebutton/published/video/#{meeting_id}/video-0.m4v` on your bbb server?

2023-04-21 11:27 UTC, dennis531 commented
Probably, the predefined oc workflow can not process the video. Here is my `post_publish_config.toml`:
```toml
### opencast configuration begin

# Variables for accessing Opencast
# Make sure change these to your Opencast installation
[opencast]
# Server URL
# Example: server = 'https://develop.opencast.org'
server = 'https://develop.opencast.org'

# User credentials allowed to ingest via HTTP basic
# Example: user = 'username'
# Example: password = 'password'
user = 'admin'
password = 'opencast'

# Workflow to use for ingest
# Example: workflow = 'bbb-upload'
workflow = 'fast'


# Allows you to add default Opencast roles to every recording
[defaultRoles]
# Default roles for the event, e.g. "ROLE_OAUTH_USER, ROLE_USER_BOB"
# Default: ""
readPerm = ""
writePerm = ""

# Default roles for the series, e.g. "ROLE_OAUTH_USER, ROLE_USER_BOB"
# Default: ""
seriesReadPerm = ""
seriesWritePerm = ""


# Various other options
[miscellaneous]
# Whether a new series should be created if the given one does not exist yet
# Default: false
createNewSeriesIfItDoesNotYetExist = true
```

2023-04-21 12:06 UTC, Arnei commented
BBB Version: BigBlueButton Server 2.6.1 (1074)

I can locate a `video-0.m4v` file.

I've also set my server to `develop.opencast.org` and used the `fast` workflow.

2023-04-24 06:30 UTC, dennis531 commented
Oh, I wrongly understood that the new format does not work. The code of the old format should be nearly untouched. Maybe your BBB is not configured correctly. I received my BBB test system from Timo.

@tibroc Have you seen the mentioned error before?

2023-05-16 07:22 UTC, dennis531 commented
Finally, I found the problem. The processing scripts for `presentation` were disabled by the command `sudo bbb-record --disable presentation` in https://github.com/elan-ev/bbb_oc_integration/blob/main/tasks/post_archive.yml#L47-L50. After enabling the scripts with `sudo bbb-record --enable presentation` both files will be processed by opencast without errors.

I am wondering why BBB is running the `post_publish` script with `presentation` as argument when `presentation`scripts are disabled.

2023-05-16 07:41 UTC, Arnei commented
> Finally, I found the problem. The processing scripts for `presentation` were disabled by the command `sudo bbb-record --disable presentation` in https://github.com/elan-ev/bbb_oc_integration/blob/main/tasks/post_archive.yml#L47-L50. After enabling the scripts with `sudo bbb-record --enable presentation` both files will be processed by opencast without errors.
> 
> I am wondering why BBB is running the `post_publish` script with `presentation` as argument when `presentation`scripts are disabled.

Nice, good find. Maybe add a note about it to the PR, so that other users who like to try out by post-publish and post-archive have an easier time avoiding this problem?

2023-05-16 08:12 UTC, Arnei commented
Ah, seems I worded that badly. What I was suggesting was adding it to the ReadMe. Best not to expect users will immediately  find some old PR description.

2023-05-16 09:47 UTC, Arnei approved these changes

2023-05-16 09:47 UTC, merged